language: python
python:
  - "2.7"
before_install:
  # Get the GeoIP database needed for the tests
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - gunzip GeoIP.dat.gz
  - sudo mv GeoIP.dat src/tests/test_data/
install: "pip install -r requirements/requirements-test.txt --use-mirrors"
services:
  - ElasticSearch
  - Redis
before_script:
  # Get master branch of rediscluster
  - git clone https://github.com/salimane/rediscluster-py.git && cd rediscluster-py && python setup.py install && cd ..
script: nosetests -w src/tests
